#!/usr/bin/env node
/**
 * sync-skills.js
 *
 * Scans skills/ directory, parses SKILL.md frontmatter, and auto-generates:
 *   1. client/src/lib/skills-data.ts  — the single source of truth for the website
 *   2. Updates skill count in client/index.html meta tags
 *   3. Updates client/public/sitemap.xml with all skill URLs
 *
 * Run: node scripts/sync-skills.js
 * Called automatically via `npm run prebuild` or GitHub Action on PR merge.
 */

import { readdirSync, readFileSync, writeFileSync, existsSync } from "fs";
import { join, resolve } from "path";
import { fileURLToPath } from "url";
import { execSync } from "child_process";

const __dirname = resolve(fileURLToPath(import.meta.url), "..");
const ROOT = resolve(__dirname, "..");
const SKILLS_DIR = join(ROOT, "skills");
const OUTPUT_TS = join(ROOT, "client/src/lib/skills-data.ts");
const INDEX_HTML = join(ROOT, "client/index.html");
const SITEMAP = join(ROOT, "client/public/sitemap.xml");
const META_FILE = join(ROOT, "scripts/skills-meta.json");

// ── Parse YAML-like frontmatter (simple parser, no deps) ──────────────────
function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};
  const yaml = match[1];
  const result = {};
  let currentKey = null;
  let currentArray = null;

  for (const line of yaml.split("\n")) {
    // Top-level key: value
    const kvMatch = line.match(/^(\w[\w-]*):\s*(.+)/);
    if (kvMatch) {
      const [, key, rawVal] = kvMatch;
      let val = rawVal.trim();
      // Remove quotes
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      // Inline array: [a, b, c]
      if (val.startsWith("[") && val.endsWith("]")) {
        val = val.slice(1, -1).split(",").map((s) => s.trim().replace(/^["']|["']$/g, ""));
      }
      result[key] = val;
      currentKey = key;
      currentArray = null;
      continue;
    }
    // Nested key under metadata.hermes — grab tags, category
    const nestedKv = line.match(/^\s+(tags|category|requires_tools):\s*(.+)/);
    if (nestedKv) {
      const [, key, rawVal] = nestedKv;
      let val = rawVal.trim();
      if (val.startsWith("[") && val.endsWith("]")) {
        val = val.slice(1, -1).split(",").map((s) => s.trim().replace(/^["']|["']$/g, ""));
      }
      result[key] = val;
      continue;
    }
    // Array item
    const arrItem = line.match(/^\s+-\s+(.+)/);
    if (arrItem && currentKey) {
      if (!Array.isArray(result[currentKey])) {
        result[currentKey] = [];
      }
      result[currentKey].push(arrItem[1].trim());
    }
  }
  return result;
}

// ── Convert kebab-case to Title Case ──────────────────────────────────────
function toDisplayName(name) {
  return name
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

// ── Load existing meta overrides ──────────────────────────────────────────
function loadMeta() {
  if (existsSync(META_FILE)) {
    return JSON.parse(readFileSync(META_FILE, "utf-8"));
  }
  return {};
}

// ── Main ──────────────────────────────────────────────────────────────────
function main() {
  const skillDirs = readdirSync(SKILLS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort();

  const meta = loadMeta();
  const skills = [];

  for (let i = 0; i < skillDirs.length; i++) {
    const dirName = skillDirs[i];
    const skillMdPath = join(SKILLS_DIR, dirName, "SKILL.md");
    if (!existsSync(skillMdPath)) {
      console.warn(`⚠ Skipping ${dirName}: no SKILL.md found`);
      continue;
    }

    const content = readFileSync(skillMdPath, "utf-8");
    const fm = parseFrontmatter(content);
    const override = meta[dirName] || {};

    skills.push({
      id: i + 1,
      name: dirName,
      displayName: override.displayName || toDisplayName(dirName),
      description: override.description || fm.description || "",
      category: override.category || fm.category || "other",
      author: fm.author || override.author || "hermeshub",
      version: fm.version || "1.0.0",
      license: fm.license || "MIT",
      compatibility: fm.compatibility || null,
      tags: fm.tags || [],
      installCount: override.installCount || 100,
      securityStatus: "verified",
      featured: override.featured !== undefined ? override.featured : false,
      repoUrl: "https://github.com/amanning3390/hermeshub",
    });
  }

  const count = skills.length;
  console.log(`✅ Found ${count} skills: ${skills.map((s) => s.name).join(", ")}`);

  // ── Generate skills-data.ts ────────────────────────────────────────────
  const tsContent = `// AUTO-GENERATED by scripts/sync-skills.js — do not edit manually.
// Run \`node scripts/sync-skills.js\` or \`npm run sync\` to regenerate.

export interface Skill {
  id: number;
  name: string;
  displayName: string;
  description: string;
  category: string;
  author: string;
  version: string;
  license: string | null;
  compatibility: string | null;
  tags: string[] | null;
  installCount: number;
  securityStatus: string;
  featured: boolean;
  skillMd: string;
  repoUrl: string | null;
  installCommand: string | null;
}

const BASE_INSTALL = "hermes skills install github:amanning3390/hermeshub/skills/";

export const skills: Skill[] = [
${skills
  .map(
    (s) => `  {
    id: ${s.id},
    name: ${JSON.stringify(s.name)},
    displayName: ${JSON.stringify(s.displayName)},
    description: ${JSON.stringify(s.description)},
    category: ${JSON.stringify(s.category)},
    author: ${JSON.stringify(s.author)},
    version: ${JSON.stringify(s.version)},
    license: ${JSON.stringify(s.license)},
    compatibility: ${JSON.stringify(s.compatibility)},
    tags: ${JSON.stringify(s.tags)},
    installCount: ${s.installCount},
    securityStatus: ${JSON.stringify(s.securityStatus)},
    featured: ${s.featured},
    skillMd: "",
    repoUrl: ${JSON.stringify(s.repoUrl)},
    installCommand: BASE_INSTALL + ${JSON.stringify(s.name)},
  }`
  )
  .join(",\n")}
];

// Load SKILL.md content from GitHub when viewing a specific skill
export async function loadSkillMd(name: string): Promise<string> {
  try {
    const response = await fetch(
      \`https://raw.githubusercontent.com/amanning3390/hermeshub/main/skills/\${name}/SKILL.md\`
    );
    if (response.ok) {
      return await response.text();
    }
  } catch (e) {
    // fallback
  }
  return \`# \${name}\\n\\nSKILL.md content is available in the GitHub repository.\\n\\nView source: https://github.com/amanning3390/hermeshub/tree/main/skills/\${name}\`;
}

export function getSkills(): Skill[] {
  return [...skills].sort((a, b) => b.installCount - a.installCount);
}

export function getFeaturedSkills(): Skill[] {
  return skills.filter((s) => s.featured).sort((a, b) => b.installCount - a.installCount);
}

export function getSkillByName(name: string): Skill | undefined {
  return skills.find((s) => s.name === name);
}

export function getSkillsByCategory(category: string): Skill[] {
  return skills.filter((s) => s.category === category).sort((a, b) => b.installCount - a.installCount);
}

export function searchSkills(query: string): Skill[] {
  const q = query.toLowerCase();
  return skills.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.displayName.toLowerCase().includes(q) ||
      s.description.toLowerCase().includes(q) ||
      s.category.toLowerCase().includes(q) ||
      (s.tags && s.tags.some((t) => t.toLowerCase().includes(q)))
  );
}
`;

  writeFileSync(OUTPUT_TS, tsContent, "utf-8");
  console.log(`📝 Generated ${OUTPUT_TS}`);

  // ── Update index.html meta tags ────────────────────────────────────────
  if (existsSync(INDEX_HTML)) {
    let html = readFileSync(INDEX_HTML, "utf-8");
    // Replace skill count in OG description
    html = html.replace(
      /(\d+) verified skills/g,
      `${count} verified skills`
    );
    writeFileSync(INDEX_HTML, html, "utf-8");
    console.log(`📝 Updated skill count in ${INDEX_HTML} → ${count}`);
  }

  // ── Update sitemap.xml ─────────────────────────────────────────────────
  if (existsSync(SITEMAP)) {
    const today = new Date().toISOString().slice(0, 10);
    const skillUrls = skills
      .map(
        (s) => `  <url>
    <loc>https://hermeshub.xyz/#/skill/${s.name}</loc>
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>`
      )
      .join("\n");

    const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.w3.org/2000/01/sitemap.xsd">
  <url>
    <loc>https://hermeshub.xyz/</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://hermeshub.xyz/#/browse</loc>
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>0.9</priority>
  </url>
  <url>
    <loc>https://hermeshub.xyz/#/submit</loc>
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
${skillUrls}
</urlset>
`;
    writeFileSync(SITEMAP, sitemap, "utf-8");
    console.log(`📝 Updated ${SITEMAP} with ${count} skill URLs`);
  }

  // ── Save meta file if it doesn't exist (bootstrap) ────────────────────
  if (!existsSync(META_FILE)) {
    const metaObj = {};
    for (const s of skills) {
      metaObj[s.name] = {
        displayName: s.displayName,
        featured: s.featured,
        installCount: s.installCount,
        category: s.category,
      };
    }
    writeFileSync(META_FILE, JSON.stringify(metaObj, null, 2) + "\n", "utf-8");
    console.log(`📝 Created ${META_FILE} — edit this to customize featured/installCount/displayName`);
  }

  // ── Regenerate OG image with current skill count ───────────────────────
  const ogScript = join(ROOT, "scripts/generate-og.py");
  if (existsSync(ogScript)) {
    try {
      console.log(`\n🖼 Regenerating OG image with ${count} skills...`);
      execSync(`python3 "${ogScript}" ${count}`, {
        cwd: ROOT,
        stdio: "inherit",
      });
    } catch (_) {
      try {
        execSync(`python "${ogScript}" ${count}`, {
          cwd: ROOT,
          stdio: "inherit",
        });
      } catch (_e) {
        console.warn("⚠ OG image generation skipped (Python/Pillow not available)");
      }
    }
  }

  console.log(`\n✅ Sync complete: ${count} skills`);
}

main();
